Add Flow UUID and Rule UUID
nufuturo-ufcg/LuLu pull request #2
Opened 2024-06-14 14:04 UTC by winiciusallan

According to the RFC logs, the information mentioned in the title has been added. This will assist in log analysis and simplify the filtering process.

2024-06-19 13:07 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +    os_log_debug(logHandle, "RULE_ID=%{public}@ adding rule: %{public}@ -> %{public}@", rule.uuid, rule.key, rule);
Isso não deveria seguir o RFC? No caso, seria INFO, não?

2024-06-19 13:08 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +    os_log_debug(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ checking %{public}@ against %{public}@ and just %{public}@", flowUUID, rule.uuid, rule.endpointAddr, endpointNames, rule.endpointHos
INFO?

2024-06-19 13:08 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +        os_log_debug(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ rule's endpoint address is a regex...", flowUUID, rule.uuid);
INFO? Revisar todas as chamadas.

2024-06-19 13:08 UTC, joaoarthurbm requested changes
Seguir o RFC quanto ao nível das chamadas de log.

2024-07-25 14:15 UTC, joaoarthurbm commented on LuLu/App/App.entitlements
> +		<string>$(TeamIdentifierPrefix)com.objective-see.lulu</string>
reverteu essa mudança mesmo? não deveria ser nufuturo....?

2024-07-25 14:17 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +                    os_log_info(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ address and port set, will check both for match", flowUUID, rule.uuid);
Essa eu acho que deveria ser debug.

2024-07-25 14:18 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +                    os_log_info(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ rule address is any ('*'), will check port", flowUUID, rule.uuid);
essa eu acho que deveria ser debug. a de baixo é a mesma coisa, mas sem a informação "vou checar..."

2024-07-25 14:18 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +                    os_log_info(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ rule port is any ('*'), will check host/url", flowUUID, rule.uuid);
essa acho que deveria ser debug

2024-07-25 14:19 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +        os_log_info(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ rule's endpoint address is a regex...", flowUUID, rule.uuid);
debug?

2024-07-25 14:20 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +            os_log_info(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ also checking %{public}@ vs. %{public}@", flowUUID, rule.uuid, url.host, rule.endpointHost);
faz sentido remover o `also` para manter o padrão da anterior?

2024-07-25 14:21 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +            os_log_info(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ checking %{public}@ vs. %{public}@", flowUUID, rule.uuid, endpointName, rule.endpointAddr);
essas "checking", na minha opinião, deveriam ser debug, também. No log info a gente só quer algo do tipo: acesso, regra, veredito.

2024-07-25 14:21 UTC, joaoarthurbm commented on LuLu/Extension/Rules.m
> +            os_log_info(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ also checking %{public}@ vs. %{public}@", flowUUID, rule.uuid, url.host, rule.endpointHost);
essas "checking", na minha opinião, deveriam ser debug, também. No log info a gente só quer algo do tipo: acesso, regra, veredito.

2024-07-25 14:22 UTC, joaoarthurbm requested changes
Muita coisa pode ser debug. Anotei inline.

Bom trabalho até aqui.

2024-07-25 17:07 UTC, winiciusallan commented on LuLu/App/App.entitlements
> +		<string>$(TeamIdentifierPrefix)com.objective-see.lulu</string>
deveria! esse pull request não deveria conter esses arquivos que vieram por conta de outra branch. estava tentando remover e devo ter revertido as mudanças por engano.

2024-07-25 17:29 UTC, winiciusallan commented
> Muita coisa pode ser debug. Anotei inline.
> 
> Bom trabalho até aqui.

A maioria das mudanças que eu fiz foi apenas incremental, não fiz alteração nas mensagens que já existem. Acho que um esforço que pode ser colocado depois é o de melhorar as próprias mensagens de debug. wdyt?

De toda forma, fiz as alterações.

2024-07-25 17:42 UTC, winiciusallan commented on LuLu/Extension/Rules.m
> +        os_log_info(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ rule's endpoint address is a regex...", flowUUID, rule.uuid);
aqui acho que pode se encaixar como info ja que não se trata de algo do código em si.

2024-07-25 17:46 UTC, winiciusallan commented on LuLu/Extension/Rules.m
> +            os_log_info(logHandle, "FLOW_ID=%{public}@ RULE_ID=%{public}@ also checking %{public}@ vs. %{public}@", flowUUID, rule.uuid, url.host, rule.endpointHost);
removi o `also` e troquei para debug. faz mais sentido assim mesmo. os proximos commits devem vir com esse tipo de log info.

2024-07-25 19:08 UTC, joaoarthurbm approved these changes
Excelente trabalho!

2024-08-06 14:20 UTC, merged